### ISSUE TITLE
번역 : Concurrency

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#11]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/concurrency.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/concurrency.md

**Comment by MiryangJung** [comment]
제가 하겠습니다.

**Comment by HongYeseul** [comment]
안녕하세요! 해당 페이지 번역에 기여 해 보고싶습니다 😄

**Comment by MiryangJung** [comment]
네 감사합니다! 번역규칙 참고해주세요.
