### ISSUE TITLE
번역 : Select

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#12]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/select.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/select.md

**Comment by alstn2468** [comment]
제가 진행하겠습니다~!

**Comment by MiryangJung** [comment]
네 감사합니다! [번역 규칙](https://github.com/MiryangJung/learn-go-with-tests-ko#%EB%B2%88%EC%97%AD-%EA%B8%B0%EC%97%AC) 참고해주세요!

**Comment by alstn2468** [comment]
요 번역은 `Integers` 챕터가 머지 된 이후에 진행하도록 하겠습니다~
