### ISSUE TITLE
번역 : Intro

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#18]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/app-intro.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/app-intro.md

**Comment by 14hhan** [comment]
제가 하겠습니다!

**Comment by MiryangJung** [comment]
네 감사합니다! [번역 규칙](https://github.com/MiryangJung/learn-go-with-tests-ko#%EB%B2%88%EC%97%AD-%EA%B8%B0%EC%97%AC) 참고해주세요!

**Comment by 14hhan** [comment]
[README.md의 일부분](https://github.com/MiryangJung/learn-go-with-tests-ko/blob/09e5a54e9025c47cd70eb43d3c8f3dc2949f5917/ko-KR/README.md#%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98-%EB%A7%8C%EB%93%A4%EA%B8%B0)이 이 챕터와 내용이 완전히 동일한 것 같은데, 이미 번역이 되어있네요!
