### ISSUE TITLE
번역 : HTTP server

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#19]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/http-server.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/http-server.md

**Comment by nicewook** [comment]
이건 제가 맡아서 해보겠습니다. 
원본 링크: https://github.com/quii/learn-go-with-tests/blob/main/http-server.md

**Comment by MiryangJung** [comment]
감사합니다!

**Comment by MiryangJung** [comment]
번역 중에 죄송합니다. 문체 통일을 위해 변경을 했으니 참고부탁드립니다. [번역 규칙](https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/README.md#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)

**Comment by nicewook** [comment]
확인했습니다. 문체 통일에 동의합니다. 
다만 의견을 드리자면 번역체는 `"니다"`, `"세요"` 보다는 `"다"`로 끝내는 것이 낫다고 생각합니다. 

1. 대부분의 기술서 번역을 보면 그렇게 되어 있었습니다.
2. 종종, 특히나 일본 서적의 번역이  `"니다"`, `"세요"` 형태인 경우가 많은데 읽다보면 편하고 부드러운 느낌은 받지만 정작 정보전달에 방해가 된다 싶습니다. 즉, 단정적이고 단호하며 간결한 문체가 기술서적에는 더욱 어울린다는 것입니다.

**Comment by MiryangJung** [comment]
의견 감사합니다. 해당 사항에 대해 이슈를 올려 진행하도록 하겠습니다!
