### ISSUE TITLE
번역 : Command line & package structure

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#22]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/command-line.md

**Comment by WHYjun** [comment]
[https://github.com/quii/learn-go-with-tests/blob/main/command-line.md](https://github.com/quii/learn-go-with-tests/blob/main/command-line.md)

이 문서인지 확인만 해주시면 제가 번역해보겠습니다.

**Comment by ChobobDev** [comment]
네, 그럼 번역 부탁드리겠습니다.

**Comment by ChobobDev** [comment]
[번역규칙 ](https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/README.md#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)한번 읽으시고 진행해주시면 감사하겠습니다.

**Comment by MiryangJung** [comment]
> https://github.com/quii/learn-go-with-tests/blob/main/command-line.md
> 
> 이 문서인지 확인만 해주시면 제가 번역해보겠습니다.

네맞습니다!
