### ISSUE TITLE
번역 : OS Exec

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#25]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/os-exec.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/os-exec.md

**Comment by qqskda** [comment]
제가 하겠습니다 :)

**Comment by MiryangJung** [comment]
네 감사합니다.
