### ISSUE TITLE
번역 : Error types

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#26]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/error-types.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/error-types.md

**Comment by heojay** [comment]
안녕하세요, 해당 파트를 제가 번역해봐도 될까요?

**Comment by MiryangJung** [comment]
네 감사합니다! [번역 규칙](https://github.com/MiryangJung/learn-go-with-tests-ko#%EB%B2%88%EC%97%AD-%EA%B8%B0%EC%97%AC) 참고해주세요!
