### ISSUE TITLE
번역 : Revisiting HTTP Handlers

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#28]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/http-handlers-revisited.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/http-handlers-revisited.md

**Comment by qqskda** [comment]
제가 작업하겠습니다 :)

**Comment by changjunpyo** [comment]
네 감사합니다!
