### ISSUE TITLE
번역 : Integers

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#3]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/integers.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/integers.md

**Comment by alstn2468** [comment]
제가 진행해도 괜찮을까요?

**Comment by MiryangJung** [comment]
네! 감사합니다.

**Comment by alstn2468** [comment]
@MiryangJung 혹시 번역 규칙 같은게 존재할까요?
ex) 제목은 영문을 유지한다. 기술적 용어에 관한 규칙, 어투에 관한 규칙 등등

**Comment by MiryangJung** [comment]
해당 부분을 명시하지 않았네요! [번역규칙](https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/README.md) 을 업데이트하였습니다.

**Comment by MiryangJung** [comment]
번역 중에 죄송합니다. 문체 통일을 위해 변경을 했으니 참고부탁드립니다. [번역 규칙](https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/README.md#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)
