### ISSUE TITLE
의견 : 중복되는 헤딩 번역 관련

### ISSUE THREAD

**Issue by qqskda** [MiryangJung/learn-go-with-tests-ko#31]
다음과 같이 여러 다른 Contents 에서 반복적으로 나타나는 헤딩의 경우 번역을 미리 해두는게 어떨까요?

_Write the minimal amount of code for the test to run and check the output_

_Write enough code to make it pass_

**Comment by MiryangJung** [comment]
좋은 생각입니다. 반복적으로 나타나는 문장들을 모으기 위한 아이디어가 있을까요?

**Comment by qqskda** [comment]
반복적으로 사용된 헤딩들의 경우 Original repo 에서 Documentation 할때 가이드라인을 잡고 진행하지 않았을까요?

추가: [template.md](https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/template.md) 에서 확인 할 수 있는것 같아요!

**Comment by MiryangJung** [comment]
아 제가 template를 확인못했네요! 알려주셔서 감사합니다.

**Comment by MiryangJung** [comment]
자주 사용되는 단어나 문장은 [구글 시트](https://docs.google.com/spreadsheets/d/1qfcrSu5CWjU3WmAQ_NSRIMxWj7dKtLd7dDmLEz28ThY/edit?usp=sharing) 에서 정리 중입니다.
