### ISSUE TITLE
모집 : 해당 프로젝트의 collaborator를 구합니다.

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#34]
제가 혼자서 관리를 하기엔 역량이 부족해서 혹시 매니징하실 분이 계시다면 collaborators 에 추가하겠습니다.

1. git, github 에 익숙한 사람
2. 번역 작업에 익숙한 사람
3. 일주일에 2번은 관리할 수 있는 사람

감사합니다.

**Comment by 14hhan** [comment]
저 지원하고 싶습니다!

**Comment by MiryangJung** [comment]
> 저 지원하고 싶습니다!

collaborator 에 추가해드렸습니다.

이슈, PR 관리 틈틈이 해주시면 감사합니다.

**Comment by changjunpyo** [comment]
저도 할 수 있다면 하고 싶습니다!

**Comment by alstn2468** [comment]
여석이 있다면 지원해보겠습니다~!

**Comment by MiryangJung** [comment]
> 저도 할 수 있다면 하고 싶습니다!

> 여석이 있다면 지원해보겠습니다~!


collaborator 에 추가해드렸습니다.

이슈, PR 관리, 번역 리뷰 틈틈이 해주시면 감사합니다.

**Comment by ChobobDev** [comment]
저도 가능하다면 하고싶습니다!

**Comment by MiryangJung** [comment]
> 저도 가능하다면 하고싶습니다!

collaborator 에 추가해드렸습니다.

이슈, PR 관리, 번역 리뷰 틈틈이 해주시면 감사합니다.

**Comment by MiryangJung** [comment]
콜라버레이터가 더 필요할 때까지 이슈는 닫습니다.
