### ISSUE TITLE
의견 : 번역 문체에 대해서

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#37]
확인했습니다. 문체 통일에 동의합니다. 
다만 의견을 드리자면 번역체는 `"니다"`, `"세요"` 보다는 `"다"`로 끝내는 것이 낫다고 생각합니다. 

1. 대부분의 기술서 번역을 보면 그렇게 되어 있었습니다.
2. 종종, 특히나 일본 서적의 번역이  `"니다"`, `"세요"` 형태인 경우가 많은데 읽다보면 편하고 부드러운 느낌은 받지만 정작 정보전달에 방해가 된다 싶습니다. 즉, 단정적이고 단호하며 간결한 문체가 기술서적에는 더욱 어울린다는 것입니다.

_Originally posted by @nicewook in https://github.com/MiryangJung/learn-go-with-tests-ko/issues/19#issuecomment-798501626_

---

번역 문체에 대해서 의견을 주시면 감사하겠습니다.

1. `니다` `세요` [예시](https://cloud.google.com/go/docs/setup?hl=ko) 사용
2. `다` [예시](https://ultimate-go-korean.github.io/translation/) 사용

**Comment by nicewook** [comment]
감사합니다. 최종 의견에 따르겠습니다. 
각자의 생각은 다를 수 있겠습니다만 현재 책장에 꽃힌 SW 개발서적의 문체만 확인해서 데이터를 모아보는 것도 좋겠습니다.

우선 저부터 번역서 몇 권 찾아봅니다. 
## "다"
- 훌륭한 프로그래머 되는 법
- 익스트림 프로그래밍
- 읽기 좋은 코드가 좋은 코드다 
- 클린 아키텍처
- 클린 애자일
- 리팩터링 2판

**Comment by alstn2468** [comment]
번역 문체와 관련이 없을 수 있지만 자주 등장하는 용어 또한 통일해야할 것 같습니다.
ex) `arguments` -> 인수? 인자?

**Comment by MiryangJung** [comment]
`슬랙` 채널에서 투표를 통해 번역 문체는 `다` 로 결정되었습니다.
