### ISSUE TITLE
의견 : 자주 사용되는 단어, 문장 번역

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#40]
번역 문체와 관련이 없을 수 있지만 자주 등장하는 용어 또한 통일해야할 것 같습니다.
ex) `arguments` -> 인수? 인자?

_Originally posted by @alstn2468 in https://github.com/MiryangJung/learn-go-with-tests-ko/issues/37#issuecomment-799006530_

---

자주 사용되는 단어나 문장은 템플릿이나 단어장으로 미리 번역을 해야될 듯합니다.
어떻게 진행할 지 의견이 필요합니다.

**Comment by alstn2468** [comment]
자주 쓰이는 단어들을 추려서 이 이슈에 목록화 한 후에 공통적으로 번역하고 메인 리드미에 추가하면 될 것 같아요~~

**Comment by MiryangJung** [comment]
1. `templates.md` 생성
2. issue를 올리고, pr을 통해 단어 및 문장 정리
3. 슬랙 또는 gitter 방을 만들어서 단어 및 문장 정리

어떠신가요? 2번과 3번은 택1로 진행하는 것이 좋을 듯합니다.

**Comment by alstn2468** [comment]
커뮤니케이션 코스트를 줄이는 방법으로는 저는 3번이 좋을 것 같다는 생각이 있긴한데.
모든 컨트리뷰터 분들이 들어오는게 쉽지는 않을 것 같다는 생각은 있어요!
3번 + 1번 방법으로 커뮤니케이션을 위한 플랫폼을 사용하고 거기에서 협의된 내용을 `templates.md`에 정리하는게 어떨까요?

**Comment by MiryangJung** [comment]
좋습니다. 일단 커뮤니케이션을 위한 플랫폼부터 정할 이슈를 올리도록 하겠습니다.

**Comment by nicewook** [comment]
우선 자주 마주치는 헤딩을 여기다 올려보겠습니다. 

## Write the test first
## Try to run the test
## Write the minimal amount of code for the test to run and check the failing test output
## Write enough code to make it pass
## Refactor
## Wrapping up

**Comment by MiryangJung** [comment]
자주 사용되는 단어나 문장 템플릿을 정리할 템플릿은 구글시트에 정리하겠습니다.
해당 사항은 `슬랙` 에서 투표로 결정되었습니다.

https://docs.google.com/spreadsheets/d/1qfcrSu5CWjU3WmAQ_NSRIMxWj7dKtLd7dDmLEz28ThY/edit?usp=sharing

기본 권한은 댓글 사용자이며, 번역에 참여하시는 분들 중에 해당 시트에 직접 참여를 하고 싶으신 분들은 슬랙채널에서 스레드에 메일을 남겨주시면 사용자로 초대하도록 하겠습니다.
