### ISSUE TITLE
의견 : 커뮤니케이션(대화, 토론)을 위한 플랫폼 정하기

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#41]
커뮤니케이션 코스트를 줄이는 방법으로는 저는 3번이 좋을 것 같다는 생각이 있긴한데.
모든 컨트리뷰터 분들이 들어오는게 쉽지는 않을 것 같다는 생각은 있어요!
3번 + 1번 방법으로 커뮤니케이션을 위한 플랫폼을 사용하고 거기에서 협의된 내용을 `templates.md`에 정리하는게 어떨까요?

_Originally posted by @alstn2468 in https://github.com/MiryangJung/learn-go-with-tests-ko/issues/40#issuecomment-799045939_

---

1. `슬랙` : 기존에 사용하는 분들이 많아 접근성 용이, 참여를 해야만 대화를 볼 수 있음
2. `gitter` : 사용하지 않는 분들이 많아 정전이 될 가능성, 참여를 하지 않아도 대화를 볼 수 있음

추가 다른 플랫폼 추천도 가능합니다.

**Comment by 14hhan** [comment]
저는 슬랙이 좋을 것 같습니다! 커뮤니케이션 플랫폼에서 협의된 내용이 `templates.md`에 정리가 되기 때문에, 개인적으로 직접 참여하지 않아도 대화를 볼 수 있냐 없냐 보다는 접근성(담론이 활발히 이루어질 수 있는 가능성)을 높이는 것이 더욱 중요할 것 같다고 생각해요.

**Comment by ChobobDev** [comment]
저도 슬랙이 가장 좋은 플랫폼이라고 생각합니다. 말씀하신대로 접근성이 용이하다는 점이 큰 장점이라고 생각합니다.

**Comment by MiryangJung** [comment]
1. golang korea 활성화 도모
2. golang 을 사용하는 유저들의 참여 유도

의 이유로 golang korea 슬랙에 채널을 빌려 사용하는 방안을 여쭈어서 허락을 맡은 상태입니다.

이 방안에 대해서 어떻게 생각하시나요?

**Comment by alstn2468** [comment]
좋은 방향이라고 생각합니다~

**Comment by changjunpyo** [comment]
저도 활성화 측면에서 새로 만들기보다는 golang korea 슬랙 채널에서 하는 뱡향이 좋은 것 같습니다.

**Comment by MiryangJung** [comment]
`README.md` 에 슬랙 가입 주소와 채널 이름 추가했습니다.
