### ISSUE TITLE
번역 : Arrays and slices

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#5]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/arrays-and-slices.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/arrays-and-slices.md

**Comment by ChobobDev** [comment]
제가 번역하겠습니다

**Comment by MiryangJung** [comment]
네 감사합니다.

**Comment by ChobobDev** [comment]
감사합니다!!

**Comment by MiryangJung** [comment]
번역 중에 죄송합니다. 문체 통일을 위해 변경을 했으니 참고부탁드립니다. [번역 규칙](https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/README.md#%EB%B2%88%EC%97%AD-%EA%B7%9C%EC%B9%99)

**Comment by ChobobDev** [comment]
네 확인했습니다.
