### ISSUE TITLE
번역 : Structs, methods & interfaces

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#6]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/structs-methods-and-interfaces.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/structs-methods-and-interfaces.md

**Comment by SangjunCha-dev** [comment]
제가 맡아서 번역 해볼게요

**Comment by MiryangJung** [comment]
네 감사합니다! [번역 규칙](https://github.com/MiryangJung/learn-go-with-tests-ko#%EB%B2%88%EC%97%AD-%EA%B8%B0%EC%97%AC) 참고해주세요!
