### ISSUE TITLE
번역 : Pointers & errors

### ISSUE THREAD

**Issue by MiryangJung** [MiryangJung/learn-go-with-tests-ko#7]
https://github.com/MiryangJung/learn-go-with-tests-ko/blob/master/ko-KR/pointers-and-errors.md

원본 : https://github.com/quii/learn-go-with-tests/blob/main/pointers-and-errors.md

**Comment by changjunpyo** [comment]
제가 해보겠습니다!

**Comment by MiryangJung** [comment]
네 감사합니다! [번역 규칙](https://github.com/MiryangJung/learn-go-with-tests-ko#%EB%B2%88%EC%97%AD-%EA%B8%B0%EC%97%AC) 참고해주세요!
